# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'book-mark-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftLocation', '~> 3.2.3'
	pod 'SwiftDate', '~> 5.0'
  # Pods for book-mark-ios

end
